export const sources = {
  teeth: {
    name: "Snan Al Ajouz / Old Man's Teeth (سنان العجوز)",
    origin: 'All areas of Palestine',
    url: 'https://tirazain.com/archive/p/lily-f5j49-2ydlp-jkdr3-7xj63',
  },
  cypress: {
    name: 'Sarwa / Cypress Tree Gaza (1) (سروة غزة)',
    origin: 'Gaza',
    url: 'https://tirazain.com/archive/p/lily-f5j49-2ydlp-jkdr3-x32jf',
  },
  keffiyeh: {
    name: 'Kufiya: fishnet, olive leaves and bold lines (كوفية)',
    origin: 'Hirbawi factory, Hebron (reference)',
    url: 'https://hirbawiusa.com/products/black-and-white',
  },
  olive: {
    name: 'Irq Al Zaytoun / Olive Branch (1) (عرق الزيتون)',
    origin: 'All areas of Palestine',
    url: 'https://tirazain.com/archive/p/lily-f5j49-2ydlp-jkdr3-66k56',
  },
}

export const teeth = ['a.', 'a.', 'aa']

export const cypress = [
  'aaa.a.b.bbb.',
  'a.a.a.b.b.b.',
  'aaa.a.b.bbb.',
  '...aa.bb....',
  'aaaaa.bbbbb.',
  '.....b......',
  '....b.b.....',
  '.....b......',
  '....b.a.....',
  '....b.a.....',
  '...bb.aa....',
  '...bb.aa....',
  '..bbb.aaa...',
  '..bbb.aaa...',
  '.bbbb.aaaa..',
  '.bbbb.aaaa..',
  'bbbbb.aaaaa.',
  'bbbbb.aaaaa.',
  '.....b......',
  '....b.b.....',
  '.....b......',
  '....a.b.....',
  '...aa.bb....',
  '..aaa.bbb...',
  '.aaaa.bbbb..',
  'aaaaa.bbbbb.',
  '.....b......',
  'bbbbb.aaaaa.',
  '.bbbb.aaaa..',
  '..bbb.aaa...',
  '...bb.aa....',
  '....b.a.....',
  '............',
  '............',
]

export const olive = [
  '...a...................a...',
  '...aa.................aa...',
  '...aaa...............aaa...',
  'aaa.aaa..aaaa.aaaa..aaa.aaa',
  '.aaa.aa..a..a.a..a..aa.aaa.',
  '..aaa.a..a..a.a..a..a.aaa..',
  '...aaa.a.aaaa.aaaa.a.aaa...',
  '......a.a....a....a.a......',
  '...aaa.a.aaaa.aaaa.a.aaa...',
  '..aaa.a..a..a.a..a..a.aaa..',
  '.aaa.aa..a..a.a..a..aa.aaa.',
  'aaa.aaa..aaaa.aaaa..aaa.aaa',
  '...aaa.......a.......aaa...',
  '...aa........a........aa...',
  '...a........a.a........a...',
  '...........a.a.a...........',
  '.............a.............',
  '............a.a............',
]
