export const sources = {
  teeth: {
    name: "Snan Al Ajouz / Old Man's Teeth (سنان العجوز)",
    origin: 'All areas of Palestine',
    url: 'https://tirazain.com/archive/p/lily-f5j49-2ydlp-jkdr3-7xj63',
  },
  cypress: {
    name: 'Sarwa / Cypress Tree Gaza (1) (سروة غزة)',
    origin: 'Gaza',
    url: 'https://tirazain.com/archive/p/lily-f5j49-2ydlp-jkdr3-x32jf',
  },
  keffiyeh: {
    name: 'Kufiya: fishnet, olive leaves and bold lines (كوفية)',
    origin: 'Hirbawi factory, Hebron (reference)',
    url: 'https://hirbawiusa.com/products/black-and-white',
  },
  olive: {
    name: 'Irq Al Zaytoun / Olive Branch (2) (عرق الزيتون)',
    origin: 'Ramallah',
    url: 'https://tirazain.com/archive/p/lily-f5j49-2ydlp-jkdr3-j3zn6',
  },
}

export const teeth = ['a.', 'a.', 'aa']

export const cypress = [
  'aaa.a.b.bbb.',
  'a.a.a.b.b.b.',
  'aaa.a.b.bbb.',
  '...aa.bb....',
  'aaaaa.bbbbb.',
  '.....b......',
  '....b.b.....',
  '.....b......',
  '....b.a.....',
  '....b.a.....',
  '...bb.aa....',
  '...bb.aa....',
  '..bbb.aaa...',
  '..bbb.aaa...',
  '.bbbb.aaaa..',
  '.bbbb.aaaa..',
  'bbbbb.aaaaa.',
  'bbbbb.aaaaa.',
  '.....b......',
  '....b.b.....',
  '.....b......',
  '....a.b.....',
  '...aa.bb....',
  '..aaa.bbb...',
  '.aaaa.bbbb..',
  'aaaaa.bbbbb.',
  '.....b......',
  'bbbbb.aaaaa.',
  '.bbbb.aaaa..',
  '..bbb.aaa...',
  '...bb.aa....',
  '....b.a.....',
  '............',
  '............',
]

export const olive = [
  'a.......a',
  'aa.aaa.aa',
  'aaa.a.aaa',
  'aaa.a.aaa',
  'aaa.a.aaa',
  'aaa.a.aaa',
  'aaa.a.aaa',
  '.aa.a.aa.',
  '..a.a.a..',
  '...aaa...',
  'b...a...b',
  'bb.aaa.bb',
  'bbb.a.bbb',
  'bbb.a.bbb',
  'bbb.a.bbb',
  'bbb.a.bbb',
  'bbb.a.bbb',
  '.bb.a.bb.',
  '..b.a.b..',
  '...aaa...',
  'c...a...c',
  'cc.aaa.cc',
  'ccc.a.ccc',
  'ccc.a.ccc',
  'ccc.a.ccc',
  'ccc.a.ccc',
  'ccc.a.ccc',
  '.cc.a.cc.',
  '..c.a.c..',
  '...aaa...',
  '....a....',
]
